export enum MESSAGE_TYPE {
  WELCOME = 1,
  REFERENCE_PLAYER_CHANGED = 2,
  SESSION_INFO = 3,
  MEDIA_CHANGED = 4,
  PLAYER_STATE_UPDATE = 5,
  CLOCK_SYNC = 6,
  REQUEST_STATE_CHANGE_PLAYING = 7,
  REQUEST_STATE_CHANGE_TIME = 8,
}
